apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: your-name
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 2
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: canary
            image: quay.io/canarytrace/smoke:c.2.12.2
            env:
            - name: BASE_URL
              value: "https://www.tesla.com/"
            - name: AVAILABILITY_CHECK
              value: allow
            - name: SMOKE
              value: allow
            - name: ELASTIC_CLUSTER
              value: http://<droplet-ip>:9200
            - name: AT_DRIVER_HOST_NAME
              value: "localhost"
            resources:
              requests:
                memory: "300Mi"
                cpu: "200m"
              limits:
                memory: "400Mi"
                cpu: "300m"
            imagePullPolicy: "Always"
          - name: selenium
            image: selenium/standalone-chrome-debug:3.141.59-20200730
            ports:
              - containerPort: 5900
              - containerPort: 4444
            resources:
              requests:
                memory: "1000Mi"
                cpu: "600m"
              limits:
                memory: "1200Mi"
                cpu: "700m"
            imagePullPolicy: "IfNotPresent"
            volumeMounts:
              - mountPath: "/dev/shm"
                name: "dshm"
            livenessProbe:
              httpGet:
                path: /wd/hub
                port: 4444
              initialDelaySeconds: 10
              timeoutSeconds: 5
            readinessProbe:
              httpGet:
                path: /wd/hub
                port: 4444
              initialDelaySeconds: 10
              timeoutSeconds: 5
          restartPolicy: "Never"
          volumes:
            - name: "dshm"
              emptyDir:
                medium: "Memory"
