apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNREE1TURReApNak15TXpKYUZ3MDBNREE1TURReE1qTXlNekphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDcEpTdjNKVkdmbnc5VG1PR09rQStxeGl6Vk9WWFVSVktPUE5oZVdZYTdHZDRDZU90egpDTVJlT0d6UEZqM0ZwZnczMXZVMEpaSjZnUld5YmlsZk5LRFlCcXZ1UmJjZmRmbkRFcS80Ri9xQit4ZlptN3l2Ck1kaENqWHFuMnVYQlZ5VlY4azQzTFBiQkZwODZDRGFiK3Y1cm55QjdTVzBWWUx3NW4rb242MlpFRy9ueVdFbGQKYU00a1k5ZHNmM3V1NEMwWkVzNXJTRjNWWDhDaFJ4c2cxbHRZSVJwV1M0MjhUeWlleU1vZGlGYWF4REpoaU9iVwpyQ05xUXZYVjNrM2E1NHhDcFVYdjNhRU1Kc1dOWFFKWGszR2ZwMTN2b3p1TDJ6YjZMT0RiSncwcWordVNtOW4wCjZ5aytQUWhmZS9UT1JlMHFSV2VWaFhQK2JSVXMyZmpHL2I1YkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFoWHpqcnd4NVJ5Ujd3bTRWVgpWeUhxNnNrbHhqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFtMVUwdWtIaUdSazQ4Um40eE0wdWdKNktNMVJoCjYwZWUwaTdaNkVHTXdhRjZ3emYxcVZJTnErL0lNQnA4amduVmM2LzNxdUlIb2RMNllXQVl4VG1jRm5BNjZoRnYKeVkvOEhHY1pyclRydll6K2MzdTFzMU1Wd3lYUUxTOXBWZFV1YWpaaGxmN05UQ3gvSWQrWm1KVUVmemFKL3FnVwpKaG43bGthNDRrNTg4eUdic1J4UUVJUFA0cWtySkRGeUxvLzBXZ1h1N2EvWnZ3cy9VV0h0d2d2UmhFa1JhVWJrCmlsUUxKQzFodFpNS0FlKzRZYjB6N2g5YW0rVVFyVDhUQ2Q1TXVxdEZjTXgraDE2YjRTbWYxZktIVUQ3TkpUVlUKc1pKQWxBOXZzM0tsQTVxbEp3TmUrR2VZRUlqSzhjK1lFZUdrbk8raDg3YkEyZU83UmE3aXZ2ZlMrQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://e1734000-3db7-4b7a-bda9-6669355c5a97.k8s.ondigitalocean.com
  name: do-fra1-equa
contexts:
- context:
    cluster: do-fra1-equa
    user: do-fra1-equa-admin
  name: do-fra1-equa
current-context: do-fra1-equa
kind: Config
preferences: {}
users:
- name: do-fra1-equa-admin
  user:
    token: 1b249755ebdeae4e57ee11c8465f62636052479e072baa64b82fd0a1ca4e2bb5
